- name: Setup base hpc
  hosts: all
  gather_facts: true
  tasks:
  - name: Add user hpc
    become: yes
    user:
      name: hpc
      shell: /bin/bash

  - name: Set SSH key
    become: yes
    authorized_key:
      user: hpc
      state: present
      key: "{{ lookup('file', '~/hpc.key.pub') }}"

  - name: Distribute private keyfiles to hosts
    become: yes
    become_user: hpc
    copy: 
      src: "~/hpc.key"
      dest: "/home/hpc/.ssh/id_dsa" 
      mode: 0600

  - name: Add hpc to sudoers
    become: yes
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "hpc  ALL=(ALL)  NOPASSWD: ALL"

  - name: Disable host SSH key checking
    become: yes
    become_user: hpc
    copy:
      dest: "~/.ssh/config"
      content: "Host *\n    StrictHostKeyChecking no\n"

  - name: apt packages
    become: yes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - cmake
      - git
      - makedepf90
      - gfortran
      - gcc
      - patch
      - unzip
      - libxtst6
      - libxt6
      # Debug stuff below
      - iptraf-ng
      - iptraf
      - iftop
      - htop
      - iotop

- name: Create a new primary partition
  parted:
    device: /dev/sdc
    number: 1
    state: present

  - name: Creating file system
    become: yes
    filesystem:
      fstype: xfs
      dev: /dev/sdc1

  - name: Mounting file system
    become: yes
    mount:
      path: /data
      src: /dev/sdc1
      fstype: xfs
      state: mounted
      backup: yes
    
  - name: Install azcopy to /usr/bin
    become: yes
    unarchive:
      src: https://aka.ms/downloadazcopy-v10-linux
      dest: /usr/bin
      creates: /usr/bin/azcopy
      remote_src: yes
      extra_opts: [--strip-components=1]
    retries: 3

  - name: Change file ownership, group and permissions
    become: yes
    file:
      path: /data
      mode: '0777'

  - name: Change file ownership, group and permissions
    become: yes
    file:
      path: /mnt
      mode: '0777'

  - name: Download blob
    become: yes
    become_user: hpc
    shell: 'azcopy copy "{{ lookup("env","SAS_RAMDAM_URL") }}" /data --recursive=true'
    args:
      creates:
        /data/ramdam

  - name: Install Matlab Runtime
    become: yes
    become_user: hpc
    shell: |
      cd /data/ramdam
      mkdir matlab
      mv MATLAB_Runtime_R2019a_Update_2_glnxa64.zip matlab
      cd matlab
      unzip MATLAB_Runtime_R2019a_Update_2_glnxa64.zip
      sudo ./install -mode silent -agreeToLicense yes
    args:
      creates: /usr/local/MATLAB/MATLAB_Runtime/v96/runtime/glnxa64/libMatlabCppSharedLib.so

  - name: Update ld.so with matlab paths
    become: yes
    copy:
      dest: /etc/ld.so.conf.d/matlab.conf
      content: |
        /usr/local/MATLAB/MATLAB_Runtime/v96/runtime/glnxa64
        /usr/local/MATLAB/MATLAB_Runtime/v96/bin/glnxa64
        /usr/local/MATLAB/MATLAB_Runtime/v96/sys/os/glnxa64
        /usr/local/MATLAB/MATLAB_Runtime/v96/extern/bin/glnxa64
        #/usr/local/MATLAB/MATLAB_Runtime/v96/opengl/bin/glnxa64

  - name: Update Workspace
    become: yes
    lineinfile:
      path: /data/ramdam/ramdam/rl_pdf/workspace_parameters.txt
      regexp: '^wkspc_param.input_dir'
      line: "wkspc_param.input_dir = '/data/ramdam/EGSL/';"

  - name: Update Workspace
    become: yes
    lineinfile:
      path: /data/ramdam/ramdam/rl_pdf/workspace_parameters.txt
      regexp: '^wkspc_param.intermed_maindir'
      line: "wkspc_param.intermed_maindir = '/mnt/intermediates/';"

  - name: Update Workspace
    become: yes
    lineinfile:
      path: /data/ramdam/ramdam/rl_pdf/workspace_parameters.txt
      regexp: '^wkspc_param.output_dir'
      line: "wkspc_param.output_dir = '/mnt/outputs/';"

  - name: Update Workspace
    become: yes
    lineinfile:
      path: /data/ramdam/ramdam/rl_pdf/workspace_parameters.txt
      regexp: '^wkspc_param.toolboxes_dir'
      line: "wkspc_param.toolboxes_dir = '/data/ramdam/ramdam/toolboxes/';"
        
  - name: Update Workspace
    become: yes
    lineinfile:
      path: /data/ramdam/ramdam/rl_pdf/workspace_parameters.txt
      regexp: '^wkspc_param.logs_maindir'
      line: "wkspc_param.logs_maindir = '/mnt/logs/';"
        
  - name: Update Workspace Cores
    become: yes
    lineinfile:
      path: /data/ramdam/ramdam/rl_pdf/workspace_parameters.txt
      regexp: '^wkspc_param.n_workers'
      line: "wkspc_param.n_workers = 60;"
        

  - name: Do science
    become: yes
    become_user: hpc
    run_once: true
    shell: |
      sudo ldconfig
      mkdir /mnt/logs &> /dev/null
      mkdir /mnt/intermediates &> /dev/null
      mkdir /mnt/outputs &> /dev/null
      sudo chmod 755 -R /data
      #cd /data/ramdam/ramdam/rl_pdf/   
      #/data/ramdam/ramdam/compilation/run_main_SPL_distribution.sh /usr/local/MATLAB/MATLAB_Runtime/v96 StLawrenceGulf 16 1000 1000